---
# Laravel
## PHP >= 7.1.3
- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes


- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Replace Composer repo.packagist to internal repo.packagist
  shell: composer config -g repo.packagist composer https://packagist.phpcomposer.com

- name: Install Laravel
  composer:
      command: create-project
      arguments: laravel/laravel
      working_dir: /data/wwwroot/

# - name: Download Laravel
#   unarchive:
#       src: "{{ laravel }}"
#       dest: /data/wwwroot/
#       owner: apache
#       group: apache
#       mode: 0750
#       remote_src: yes

# - name: Rename directory name
#   shell: mv /data/wwwroot/laravel-* /data/wwwroot/laravel

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache

- name: Change 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"Laravel","switch":0,'
    line: '{"appname":"Laravel","switch":1,'   
  
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest