---
- name: app
  hosts: server
  remote_user: root

  roles:
    - { role: wordpress , tags: "wordpress"} 
    - { role: zentaoPMS , tags: "zentaoPMS"} 
    - { role: ranzhi , tags: "ranzhi"} 
    - { role: chanzhiESP , tags: "chanzhiESP"} 
    - { role: moodle, tags: "moodle"}
    - { role: owncloud, tags: "owncloud"}
    - { role: nextcloud, tags: "nextcloud"}
    - { role: discuz, tags: "discuz"}

    



    


