---
- name: app
  hosts: all
  remote_user: root

  roles:
    - { role: wordpress , tags: "wordpress"} 
    - { role: zentaoPMS , tags: "zentaoPMS"} 
    - { role: ranzhi , tags: "ranzhi"} 
    - { role: chanzhiESP , tags: "chanzhiESP"} 
    - { role: moodle, tags: "moodle"}
    - { role: owncloud, tags: "owncloud"}
    - { role: nextcloud, tags: "nextcloud"}
    - { role: discuz, tags: "discuz"}
    - { role: EmpireCMS, tags: "EmpireCRM"}
    - { role: KODExplorer, tags: "KODExplorer"}
    - { role: MantisBT, tags: "MantisBT"}
    - { role: EspoCRM, tags: "EspoCRM"}
    - { role: Drupal, tags: "Drupal"}
    - { role: OpenCart, tags: "OpenCart"}
    - { role: Joomla, tags: "Joomla"}
    - { role: Zurmo, tags: "Zurmo"}
    - { role: Pydio, tags: "Pydio"}
    - { role: Dolibarr, tags: "Dolibarr"}
    - { role: VtigerCRM, tags: "VtigerCRM"}
    - { role: prestashop, tags: "prestashop"}
    - { role: MediaWiki, tags: "MediaWiki"}
    - { role: ThinkPHP, tags: "ThinkPHP" }
    - { role: Laravel, tags: "Laravel" }
    - { role: Portainer, tags: "Portainer" }