## 部署
- name: phpApps
  hosts: all
  become: yes
  become_method: sudo  
  vars_prompt:
    - name: 'phpapps_selection'
      prompt: "\nWhich application do you want to install? [ 1/2/3/4/5/6... ] \n\n
      1：chanzhi      2: cmseasy \n
      3: codiad       4: dolibarr \n
      5: dreamfactory 6: dzzoffice\n
      7: empirecms    8: espocrm \n
      9: kodexplore     10: laravel \n
      11: mantisbt    12: matomo \n
      13: onethink    14: pydio \n
      15: ranzhi      16: resourcespace \n
      17: suitecrm    18: symfony\n
      19: testlink    20: thinkcmf \n
      21: thinkphp    22: vanilla\n
      23: vtigercrm   24: zurmo\n\n"
      private: no
      default: 1
    
    - name: 'webs_selection'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n\n"
      private: no
      default: 1

  vars:
    select_phpapps:
      '1':
        name: chanzhi
        mysqlver: "5.7"
        phpver: "7.2"
        documentroot: "www"
        
      '2':
        name: cmseasy
        mysqlver: "5.7"
        phpver: "7.2"

    select_webs:
      '1': 'apache'
      '2': 'nginx'
    
    mysql_version: "{{select_phpapps[phpapps_selection].mysqlver}}" 
    php_version: "{{select_phpapps[phpapps_selection].phpver}}" 
    phpapps_name: "{{select_phpapps[phpapps_selection].name}}" 
    phpapps_documentroot: "{{select_phpapps[phpapps_selection].documentroot}}"
    phpapps_webs: "{{select_webs[webs_selection]}}"    
  
  vars_files:
    - vars/main.yml

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache, tags: "role_apache", when: moodle_webs == 'apache'}
    - {role: role_nginx, tags: "role_nginx", when: moodle_webs == 'nginx'}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_php-fpm, tags: "role_php-fpm"}
    - {role: role_inotify_watch, tags: "role_inotify_watch"}
    - {role: role_lamp, tags: "role_lamp", when: moodle_webs == 'apache'}
    - {role: role_lnmp, tags: "role_lnmp", when: moodle_webs == 'nginx'}
    - {role: role_phpmyadmin, tags: "role_phpmyadmin"}
    - {role: role_9panel, tags: "role_9panel"}
    - {role: role_redis, tags: "role_redis"}
    - {role: phpapps, tags: "phpapps"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_end, tags: "end"}
