## 部署
---
- name: phpApps
  hosts: all
  become: yes
  become_method: sudo  
  vars_files:
    - vars/applications.yml

  vars_prompt:
    - name: 'phpapps_selection'
      prompt: "\nWhich application do you want to install? [ input application name... ] \n\n
      chanzhi(need ioncube)      cmseasy(ok) \n
      codiad(unavailable)      dolibarr(ok) \n
      dreamfactory(ok)      dzzoffice(ok)\n
      empirecms(ok)      espocrm(ok) \n
      kodcloud(ok)      laravel(ok) \n
      mantisbt(500 error)      matomo(ok) \n
      onethink(error)      pydio(unavailable) \n
      resourcespace(unavailable)      suitecrm(ok) \n
      symfony(ok)      testlink(unavailable)   \n
      thinkphp(ok)        thinkcmf(ok) \n
      vtigercrm(ok)         vanilla(unavailable)\n
      weengine(ok)          zdoo(need ioncube) \n   
      zurmo(unavailable)\n\n"
      private: no
      default: chanzhi
    
    - name: 'webs_selection'
      prompt: "\nWhich Web-Server do you want to use? [ 1/2 ] \n\n
      1: Apache\n
      2: Nginx\n\n"
      private: no
      default: 1

  pre_tasks:
    - debug: 
        msg: Selected application is  {{phpapps_meta[phpapps_selection].name}}

  vars:
    webs_select:
      '1': 'apache'
      '2': 'nginx'
      
    infrastructure_select:
      '1': 'LAMP'
      '2': 'LNMP'

    php_version: "{{phpapps_meta[phpapps_selection].phpver}}" 
    phpapps_name: "{{phpapps_meta[phpapps_selection].name}}"
    phpapps_title: "{{phpapps_meta[phpapps_selection].title}}"      
    phpapps_documentroot: "{{phpapps_meta[phpapps_selection].documentroot}}"
    phpapps_webs: "{{webs_select[webs_selection]}}"

    phpmyadmin_webs: "{{webs_select[webs_selection]}}" 
    w9panel_webs: "{{webs_select[webs_selection]}}" 
    
    w9panel_set_infrastructure: "{{infrastructure_select[webs_selection]}}" 
    w9panel_set_apps: 
      - "{{phpapps_meta[phpapps_selection].title}}"

    # 生成应用数据库和用户
    mysql_version: "{{phpapps_meta[phpapps_selection].mysqlver}}" 
    
    mysql_databases:
    - name: "{{phpapps_name}}"
      encoding: utf8
    
    mysql_users:
    - name: "{{phpapps_name}}"
      host: localhost
      priv: '{{phpapps_name}}.*:ALL'

    # 初始化MySQL root密码
    init_db: 
        mysql:
          user: root
          password: "123456"  
      
    # 应用数据库信息
    init_application:
      "{{phpapps_name}}":
        service: php-fpm
        database: "{{phpapps_name}}" 
        database_user: "{{phpapps_name}}"
        database_host: localhost
        database_password: "123456"
        config_path: 
          - "{{phpapps_meta[phpapps_selection].config_path}}" 

  roles:
    - {role: role_common, tags: "role_common"}
    - {role: role_cloud, tags: "role_cloud"}
    - {role: role_apache, tags: "role_apache", when: phpapps_webs == 'apache'}
    - {role: role_nginx, tags: "role_nginx", when: phpapps_webs == 'nginx'}
    - {role: role_mysql, tags: "role_mysql"}
    - {role: role_php-fpm, tags: "role_php-fpm"}
    - {role: role_inotify_watch, tags: "role_inotify_watch"}
    - {role: role_lamp, tags: "role_lamp", when: phpapps_webs == 'apache'}
    - {role: role_lnmp, tags: "role_lnmp", when: phpapps_webs == 'nginx'}
    - {role: role_phpmyadmin, tags: "role_phpmyadmin"}
    - {role: role_9panel, tags: "role_9panel"}
    - {role: role_redis, tags: "role_redis"}
    - {role: phpapps, tags: "phpapps"}
    - {role: role_init_password, tags: "role_init_password"}
    - {role: role_preend, preend_certbot: True, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
