---
# Discuz!X3.4
- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes


- name: Download Discuz!X3.4
  git:
    repo: "{{ Discuz }}"
    dest: /data/wwwroot/discuz


- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

    
- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache

- name: Change 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"Discuz","switch":0,'
    line: '{"appname":"Discuz","switch":1,'

- name: copy discuz config
  copy: src=config_global_default.php dest=/data/wwwroot/discuz/upload/config

  
- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;


- name: System Upgrade
  yum: name=* state=latest