---
- name: Download wordpress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Copy Apache Vhost Configuration
  template: src=vhost.conf dest=/etc/httpd/vhost/vhost.conf
  notify: restart Apache

- name: Create wordpress databases
  mysql_db:
    login_user: root
    login_password: 123456
    name: wordpress
    state: present

- name: generate WordPress database random password
  shell: < /dev/urandom tr -dc 0-9-A-Z-a-z-/|head -c ${1:-10};echo
  register: random_pass


- name: Create WordPress database user
  mysql_user: login_user=root login_password=123456 name=wordpress password={{ random_pass.stdout }} priv='wordpress.*:ALL' host=localhost state=present

- name: Save WordPress random pass
  shell: printf "username:wordpress\npassword:{{ random_pass.stdout }}\n" > /root/password.txt

- name: Copy WordPress config file
  template: src=wp-config.php dest=/data/wwwroot/wordpress/ owner=apache group=apache


- name: Change 9panel for Wordpress
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"WordPress","switch":0,'
    line: '{"appname":"WordPress","switch":1,'