---
- name: Download wordpress
  unarchive:
    src: "{{ WordPress }}"
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Copy Apache Vhost Configuration
  template: src=vhost.conf dest=/etc/httpd/vhost/vhost.conf
  notify: restart Apache

- name: Create wordpress databases
  mysql_db:
    login_user: root
    login_password: 123456
    name: wordpress
    state: present

- name: Copy WordPress config file
  template: src=wp-config.php dest=/data/wwwroot/wordpress/ owner=apache group=apache

- name: Copy databases initialization
  copy:
    src: init.sh
    dest: /root
    mode: 0770

- name: initialization Script Start
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0770


- name: Change 9panel 
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"WordPress","switch":0,'
    line: '{"appname":"WordPress","switch":1,'

- name: Permission
  file:
    path: /data/wwwroot
    owner: apache
    group: apache
    recurse: yes
    mode: 0750