---
# ThinkCMF

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Replace Composer repo.packagist to internal repo.packagist
  shell: composer config -g repo.packagist composer https://packagist.phpcomposer.com


- name: Create ThinkCMF directory
  file:
    path: /data/wwwroot/thinkcmf
    state: directory

- name: Download ThinkCMF
  unarchive:
      src: "{{ thinkcmf }}"
      dest: /data/wwwroot/thinkcmf
      owner: apache
      group: apache
      mode: 0750
      remote_src: yes

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache
  
- name: Change 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"ThinkCMF","switch":0,'
    line: '{"appname":"ThinkCMF","switch":1,'


- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest