---
# 禅知

- name: Download ChanZhiEPS
  unarchive:
    src: "{{ chanzhiEPS }}"
    dest: /data/wwwroot
    remote_src: yes

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache


  