---
# Opencart
##　sql文件在打包时修改
- name: Create folder
  file:
    path: /data/wwwroot/opencart1
    state: directory
    mode: 0750

- name: Download Opencart
  unarchive:
    src: "{{ OpenCart }}"
    dest: /data/wwwroot/opencart1
    owner: apache
    group: apache
    remote_src: yes

- name: move upload folder to opencart -1
  file:
    path: /data/wwwroot/opencart
    state: directory
    owner: apache
    group: apache
    mode: 0750
    remote_src: yes
    
- name: move upload folder to opencart -2
  shell: mv /data/wwwroot/opencart1/upload/* /data/wwwroot/opencart

- name: move upload folder to opencart -3
  file:
    path: /data/wwwroot/opencart1
    state: absent

- name: Rename config-dist.php to config-dist.php
  shell: cp /data/wwwroot/opencart/upload/config-dist.php /data/wwwroot/opencart/config.php
  
- name: Rename admin/config-dist.php to config-dist.php
  shell: cp /data/wwwroot/opencart/admin/config-dist.php /data/wwwroot/opencart/admin/config.php
 
- name: Download Opencart language package
  unarchive:
    src: "{{ OpenCart-language-cn }}"
    dest: /root/
    owner: apache
    group: apache
    remote_src: yes
  when: language == "cn"

- name: move language package to opencart source code
  copy:
    src: /root/opencart
    dest: /data/wwwroot/opencart
    owner: apache
    group: apache
  when: language == "cn"

- name: delete language package
  file: 
    path: /root/opencart
    state: absent
  when: language == "cn"
  
- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Create OpenCart databases
  mysql_db:
    login_user: root
    login_password: 123456
    name: opencart
    state: present

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache

- name: Change 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"Opencart","switch":0,'
    line: '{"appname":"Opencart","switch":1,'

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest