---
# OwnCloud

- name: Download OwnCloud
  unarchive:
    src: "{{ OwnCloud }}"
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache

- name: Change 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"OwnCloud","switch":0,'
    line: '{"appname":"OwnCloud","switch":1,'

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: Permission occ
  file:
    path: /data/wwwroot/owncloud/occ
    state: file
    mode: "u+x,g+x"

- name: copy config
  copy:
    src: config.php
    dest: /data/wwwroot/owncloud/config
  notify: restart redis

- name: Owncloud cron
  cron:
    name: "Owncloud cron"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: apache
    job: "php -f /data/wwwroot/owncloud/cron.php"