- debug:
    msg: cmseasy is running

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    cmseasy_vhost_dir: "{{php_runtime_meta[ansible_distribution][cmseasy_webs].vhost_dir}}"
    cmseasy_vhost_src: "{{php_runtime_meta[ansible_distribution][cmseasy_webs].vhost_src}}"
    cmseasy_service: "{{php_runtime_meta[ansible_distribution][cmseasy_webs].service}}"
    cmseasy_owner: "{{php_runtime_meta[ansible_distribution][cmseasy_webs].owner}}"
    cmseasy_title: "{{phpapps_title}}"
    cmseasy_document_root: "cmseasy/"
    cmseasy_download_url: "http://ftp.cmseasy.cn/CmsEasy7.x/CmsEasy_7.5.3_UTF-8_20200209.zip"

- debug:
    msg: runtime {{ cmseasy_vhost_dir }}, {{cmseasy_vhost_src}}, {{cmseasy_service}}, {{cmseasy_owner}}, {{cmseasy_webs}}, {{ansible_distribution}}

# 9panel
- name: Enabled 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["CmsEasy"];'

# cmseasy
- name: Create Directory
  file:
    path: /data/wwwroot/cmseasy
    state: directory
    mode: 0755
  
- name: Download and Unarchive CmsEasy
  unarchive:
    src: "{{ cmseasy_download_url }}"
    dest: /data/wwwroot/cmseasy
    remote_src: yes

- name: Copy Apache or Nginx vhost configuration
  template: src={{cmseasy_vhost_src}} dest={{cmseasy_vhost_dir}}