- debug:
    msg: cmseasy is running

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    cmseasy_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    cmseasy_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    cmseasy_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    cmseasy_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    cmseasy_name: "{{phpapps_name}}"
    cmseasy_title: "{{phpapps_title}}"
    cmseasy_download_url: "https://libs-websoft9-com.oss-accelerate.aliyuncs.com/apps/CmsEasy_7.5.4_UTF-8_20200229.zip"
    #cmseasy_download_url: "http://ftp.cmseasy.cn/CmsEasy7.x/CmsEasy_7.5.4_UTF-8_20200229.zip"

- debug:
    msg: runtime {{ cmseasy_vhost_dir }}, {{cmseasy_vhost_src}}, {{cmseasy_service}}, {{cmseasy_owner}}, {{ansible_distribution}}

# cmseasy
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{cmseasy_name}}*

- name: Create Directory for {{cmseasy_title}}
  file:
    path: /data/wwwroot/{{cmseasy_name}}
    state: directory
    mode: 0755
  
- name: Download and Unarchive for {{ cmseasy_download_url }}
  unarchive:
    src: "{{ cmseasy_download_url }}"
    dest: /data/wwwroot/{{cmseasy_name}}
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{cmseasy_name}}" ]; then mv *{{cmseasy_name}}* {{cmseasy_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{cmseasy_vhost_src}} dest={{cmseasy_vhost_dir}}
