---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    dreamfactory_vhost_dir: "{{php_runtime_meta[ansible_distribution][dreamfactory_webs].vhost_dir}}"
    dreamfactory_vhost_src: "{{php_runtime_meta[ansible_distribution][dreamfactory_webs].vhost_src}}"
    dreamfactory_service: "{{php_runtime_meta[ansible_distribution][dreamfactory_webs].service}}"
    dreamfactory_owner: "{{php_runtime_meta[ansible_distribution][dreamfactory_webs].owner}}"
    dreamfactory_document_root: "dreamfactory/"
    dreamfactory_download_url: "https://github.com/dreamfactorysoftware/dreamfactory.git"
    dreamfactory_version: "4.0.1"

- debug:
    msg: runtime {{ dreamfactory_vhost_dir }}, {{dreamfactory_vhost_src}}, {{dreamfactory_service}}, {{dreamfactory_owner}}, {{dreamfactory_webs}}, {{ansible_distribution}}

# 9panel
- name: Enabled 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["DreamFactory"];'

# dreamfactory
- name: Create Directory
  file:
    path: /data/wwwroot/dreamfactory
    state: directory
    mode: 0755
  
- name: Download dreamfactory-LMS
  git:
    repo: https://github.com/dreamfactory/dreamfactory.git
    dest: /data/wwwroot/dreamfactory
    version: "{{dreamfactory_version}}"

- name: Copy Apache or Nginx vhost configuration
  template: src={{dreamfactory_vhost_src}} dest={{dreamfactory_vhost_dir}}
