---
- debug:
    msg: dreamfactory is installing now

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    dreamfactory_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    dreamfactory_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    dreamfactory_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    dreamfactory_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    dreamfactory_name: "{{phpapps_name}}"
    dreamfactory_title: "{{phpapps_title}}"
    dreamfactory_download_url: "https://github.com/dreamfactorysoftware/dreamfactory/archive/4.0.1.zip"

- debug:
    msg: runtime {{ dreamfactory_vhost_dir }}, {{dreamfactory_vhost_src}}, {{dreamfactory_service}}, {{dreamfactory_owner}}, {{ansible_distribution}}

# dreamfactory
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{dreamfactory_name}}*

- name: Download dreamfactory
  unarchive:
    src: "{{ dreamfactory_download_url }}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{dreamfactory_name}}" ]; then mv *{{dreamfactory_name}}* {{dreamfactory_name}}; fi

- name: Replace Composer repo.packagist to internal repo.packagist
  shell: composer config -g repo.packagist composer https://packagist.phpcomposer.com

- name: install DreamFactory by composer
  composer:
    command: install
    ignore-platform-reqs: yes
    working_dir: /data/wwwroot/{{dreamfactory_name}}

- name: configure database connection by expect
  expect:
    command: php artisan df:env
    chdir: /data/wwwroot/{{dreamfactory_name}}
    responses:
      'tables': "1"
      'Host': "localhost"
      'Port': "3306"
      'name': "dreamfactory"
      'username': "dreamfactory"
      'password': "{{mysql_root_password}}"
      'Re-enter': "{{mysql_root_password}}"
    echo: yes

- name: set administrator account by expect
  expect:
    command: php artisan df:setup
    chdir: /data/wwwroot/{{dreamfactory_name}}
    responses:
      'first name': "dream"
      'last name': "factory"
      'email address': "admin@admin.com"
      'Choose': "admin123"
      'Re-enter': "admin123"
    echo: yes

- name: Copy Apache or Nginx vhost configuration
  template: src={{dreamfactory_vhost_src}} dest={{dreamfactory_vhost_dir}}
