---
- debug:
    msg: laravel is installing now

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    laravel_vhost_dir: "{{php_runtime_meta[ansible_os_family][laravel_webs].vhost_dir}}"
    laravel_vhost_src: "{{php_runtime_meta[ansible_os_family][laravel_webs].vhost_src}}"
    laravel_service: "{{php_runtime_meta[ansible_os_family][laravel_webs].service}}"
    laravel_owner: "{{php_runtime_meta[ansible_os_family][laravel_webs].owner}}"
    laravel_name: "{{phpapps_name}}"
    laravel_title: "{{phpapps_title}}"
    laravel_download_url: "https://github.com/laravel/laravel.git"

- debug:
    msg: runtime {{ laravel_vhost_dir }}, {{laravel_vhost_src}}, {{laravel_service}}, {{laravel_owner}}, {{laravel_webs}}, {{ansible_distribution}}

# 9panel
- name: Enabled 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["{{laravel_title}}"];'

# laravel
- name: Remove already existing {{laravel_name}}
  file:
    path: /data/wwwroot/{{laravel_name}}
    state: absent

- name: Replace Composer repo.packagist to internal repo.packagist
  shell: composer config -g repo.packagist composer https://packagist.phpcomposer.com

- name: Install Laravel
  composer:
      command: create-project
      arguments: laravel/laravel
      working_dir: /data/wwwroot/

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{laravel_name}}" ]; then mv *{{laravel_name}}* {{laravel_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{laravel_vhost_src}} dest={{laravel_vhost_dir}}
