---
- debug:
    msg: mantisbt is installing now

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    mantisbt_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    mantisbt_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    mantisbt_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    mantisbt_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    mantisbt_name: "{{phpapps_name}}"
    mantisbt_title: "{{phpapps_title}}"
    mantisbt_download_url: "https://github.com/mantisbt/mantisbt/archive/release-2.23.0.zip"

- debug:
    msg: runtime {{ mantisbt_vhost_dir }}, {{mantisbt_vhost_src}}, {{mantisbt_service}}, {{mantisbt_owner}}, {{ansible_distribution}}

# mantisbt
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{mantisbt_name}}*
  
- name: Download from {{ mantisbt_download_url }}
  unarchive:
    src: "{{ mantisbt_download_url }}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{mantisbt_name}}" ]; then mv *{{mantisbt_name}}* {{mantisbt_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{mantisbt_vhost_src}} dest={{mantisbt_vhost_dir}}
