---
- debug:
    msg: onethink is installing now

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    onethink_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    onethink_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    onethink_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    onethink_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    onethink_name: "{{phpapps_name}}"
    onethink_title: "{{phpapps_title}}"
    onethink_download_url: "https://github.com/liu21st/onethink/archive/1.0.131115.zip"

- debug:
    msg: runtime {{ onethink_vhost_dir }}, {{onethink_vhost_src}}, {{onethink_service}}, {{onethink_owner}}, {{ansible_distribution}}

# onethink
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{onethink_name}}*
  
- name: Download thinkcmf from {{onethink_download_url}}
  unarchive:
    src: "{{onethink_download_url}}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{onethink_name}}" ]; then mv *{{onethink_name}}* {{onethink_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{onethink_vhost_src}} dest={{onethink_vhost_dir}}
