---
- debug:
    msg: onethink is installing now

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    onethink_vhost_dir: "{{php_runtime_meta[ansible_distribution][onethink_webs].vhost_dir}}"
    onethink_vhost_src: "{{php_runtime_meta[ansible_distribution][onethink_webs].vhost_src}}"
    onethink_service: "{{php_runtime_meta[ansible_distribution][onethink_webs].service}}"
    onethink_owner: "{{php_runtime_meta[ansible_distribution][onethink_webs].owner}}"
    onethink_name: "{{phpapps_name}}"
    onethink_title: "{{phpapps_title}}"
    onethink_download_url: "https://github.com/liu21st/onethink.git"
    onethink_version: "1.0.131115"

- debug:
    msg: runtime {{ onethink_vhost_dir }}, {{onethink_vhost_src}}, {{onethink_service}}, {{onethink_owner}}, {{onethink_webs}}, {{ansible_distribution}}

# 9panel
- name: Enabled 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["{{onethink.title}}"];'

# onethink
- name: Remove already existing {{onethink_name}}
  file:
    path: /data/wwwroot/{{onethink_name}}
    state: absent

- name: Create Directory
  file:
    path: /data/wwwroot/onethink
    state: directory
    mode: 0755
  
- name: Download onethink
  git:
    repo: "{{ onethink_download_url }}"
    dest: /data/wwwroot/onethink
    version: "{{onethink_version}}"

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{onethink_name}}" ]; then mv *{{onethink_name}}* {{onethink_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{onethink_vhost_src}} dest={{onethink_vhost_dir}}
