---
- debug:
    msg: Pydio is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    pydio_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    pydio_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    pydio_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    pydio_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    pydio_name: "{{phpapps_name}}"
    pydio_title: "{{phpapps_title}}"
    pydio_download_url: "https://github.com/pydio/pydio-core/archive/pydio-core-8.2.4.zip"

- debug:
    msg: runtime {{ pydio_vhost_dir }}, {{pydio_vhost_src}}, {{pydio_service}}, {{pydio_owner}}, {{ansible_distribution}}

# pydio
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{pydio_name}}*
  
- name: Download {{pydio_name}} from {{ pydio_download_url }}
  unarchive:
    src: "{{ pydio_download_url }}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{pydio_name}}" ]; then mv *{{pydio_name}}* {{pydio_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{pydio_vhost_src}} dest={{pydio_vhost_dir}}