---
- debug:
    msg: Pydio is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    pydio_vhost_dir: "{{php_runtime_meta[ansible_distribution][pydio_webs].vhost_dir}}"
    pydio_vhost_src: "{{php_runtime_meta[ansible_distribution][pydio_webs].vhost_src}}"
    pydio_service: "{{php_runtime_meta[ansible_distribution][pydio_webs].service}}"
    pydio_owner: "{{php_runtime_meta[ansible_distribution][pydio_webs].owner}}"
    pydio_document_root: "pydio/"
    pydio_download_url: "https://github.com/pydio/pydio-core.git"
    pydio_version: "pydio-core-8.2.4"

- debug:
    msg: runtime {{ pydio_vhost_dir }}, {{pydio_vhost_src}}, {{pydio_service}}, {{pydio_owner}}, {{pydio_webs}}, {{ansible_distribution}}

# 9panel
- name: Enabled 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Pydio"];'

# pydio
- name: Create Directory
  file:
    path: /data/wwwroot/pydio
    state: directory
    mode: 0755
  
- name: Download pydio
  git:
    repo: https://github.com/zyx0814/pydio.git
    dest: /data/wwwroot/pydio
    version: "{{pydio_version}}"

- name: Copy php.ini
  copy: src=pydio_php.ini  dest=/etc/php.ini

- name: Copy Apache or Nginx vhost configuration
  template: src={{pydio_vhost_src}} dest={{pydio_vhost_dir}}