---
- debug:
    msg: resourcespace is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    resourcespace_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    resourcespace_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    resourcespace_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    resourcespace_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    resourcespace_name: "{{phpapps_name}}"
    resourcespace_title: "{{phpapps_title}}"
    resourcespace_download_url: "https://www.resourcespace.com/downloads/ResourceSpace_9_2_14536.zip"

- debug:
    msg: runtime {{ resourcespace_vhost_dir }}, {{resourcespace_vhost_src}}, {{resourcespace_service}}, {{resourcespace_owner}}, {{ansible_distribution}}

# 主任务区
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{resourcespace_name}}*

- name: Create Folder
  file:
    path: /data/wwwroot/{{resourcespace_name}}
    state: directory
    mode: 0750

- name: Download ResourceSpace
  unarchive:
    src: "{{ resourcespace_download_url }}"
    dest: /data/wwwroot/{{resourcespace_name}}
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{resourcespace_name}}" ]; then mv *{{resourcespace_name}}* {{resourcespace_name}}; fi

# Install extra dependence soft on RedHat
- block:
  - name: Install other nesscessary software
    yum:
      name: [subversion, ghostscript, ImageMagick, poppler, ]
      state: latest

  - name: Install CERT-Forensics-Tool -1 
    get_url:
        url: https://forensics.cert.org/cert-forensics-tools-release-el7.rpm
        dest: /opt/cert-forensics-tools.rpm
        mode: 0644

  - name: Install CERT-Forensics-Tool -2
    shell: rpm -i cert-forensics-tools.rpm
    args:
      chdir: /opt

  - name: Remove cert-forensics-tools.rpm
    file:
      path: /opt/cert-forensics-tools.rpm
      state: absent

  - name: Install CERT-Forensics-Tool -3
    yum:
      name: CERT-Forensics-Tools
      state: latest
      skip_broken: yes
  when: ansible_os_family == "RedHat"

- name: Create filestore directory
  file:
      path: /data/wwwroot/resourcespace/filestore
      state: directory
      mode: 0750

- name: Copy Apache or Nginx vhost configuration
  template: src={{resourcespace_vhost_src}} dest={{resourcespace_vhost_dir}}