---
- debug:
    msg: resourcespace is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    resourcespace_vhost_dir: "{{php_runtime_meta[ansible_distribution][phpapps_webs].vhost_dir}}"
    resourcespace_vhost_src: "{{php_runtime_meta[ansible_distribution][phpapps_webs].vhost_src}}"
    resourcespace_service: "{{php_runtime_meta[ansible_distribution][phpapps_webs].service}}"
    resourcespace_owner: "{{php_runtime_meta[ansible_distribution][phpapps_webs].owner}}"
    resourcespace_name: "{{phpapps-name}}"
    resourcespace_title: "{{phpapps_title}}"
    resourcespace_download_url: "http://dl.cnezsoft.com/resourcespace/5.2/resourcespace.5.2.stable.zip"

- debug:
    msg: runtime {{ resourcespace_vhost_dir }}, {{resourcespace_vhost_src}}, {{resourcespace_service}}, {{resourcespace_owner}}, {{resourcespace_webs}}, {{ansible_distribution}}

# 9panel
- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["{{resourcespace_title}}"];'

# 主任务区
- name: Remove already existing {{resourcespace_name}}
  file:
    path: /data/wwwroot/{{resourcespace_name}}
    state: absent

- name: Create Folder
  file:
    path: /data/wwwroot/resourcespace
    state: directory
    mode: 0750

- name: Download ResourceSpace
  unarchive:
    src: "{{ resourcespace_download_url }}"
    dest: /data/wwwroot/resourcespace
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{resourcespace_name}}" ]; then mv *{{resourcespace_name}}* {{resourcespace_name}}; fi

# Install extra dependence soft on RedHat
- block:
  - name: Install other nesscessary software
    yum:
      name: [subversion, ghostscript, ImageMagick, poppler, ]
      state: latest

  - name: Install CERT-Forensics-Tool -1 
    get_url:
        url: https://forensics.cert.org/cert-forensics-tools-release-el7.rpm
        dest: /opt/cert-forensics-tools.rpm
        mode: 0644

  - name: Install CERT-Forensics-Tool -2
    shell: rpm -i cert-forensics-tools.rpm
    args:
      chdir: /opt

  - name: Remove cert-forensics-tools.rpm
    file:
      path: /opt/cert-forensics-tools.rpm
      state: absent

  - name: Install CERT-Forensics-Tool -3
    yum:
      name: CERT-Forensics-Tools
      state: latest
      skip_broken: yes
  when: ansible_os_family == "RedHat"

- name: change php.ini
  copy:
    src: php.ini 
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0640

- name: Create filestore directory
  file:
      path: /data/wwwroot/resourcespace/filestore
      state: directory
      mode: 0750

- name: Copy Apache or Nginx vhost configuration
  Template: src={{resourcespace_vhost_src}} dest={{resourcespace_vhost_dir}}