---
- debug:
    msg: suitecrm is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    suitecrm_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    suitecrm_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    suitecrm_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    suitecrm_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    suitecrm_name: "{{phpapps_name}}"
    suitecrm_title: "{{phpapps_title}}"
    suitecrm_download_url: "https://suitecrm.com/files/162/SuiteCRM-7.11/513/SuiteCRM-7.11.15.zip"
                            
- debug:
    msg: runtime {{ suitecrm_vhost_dir }}, {{suitecrm_vhost_src}}, {{suitecrm_service}}, {{suitecrm_owner}}, {{ansible_distribution}}

# suitecrm
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{suitecrm_name}}*
 
- name: Download {{suitecrm_name}} from {{ suitecrm_download_url }}
  unarchive:
    src: "{{ suitecrm_download_url }}"
    dest: /data/wwwroot
    remote_src: yes

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{suitecrm_name}}" ]; then mv *SuiteCRM* {{suitecrm_name}}; fi

- name: create crontab task
  shell: echo "* * * * * cd /data/wwwroot/{{suitecrm_name}}; /usr/bin/php -f cron.php > /dev/null 2>&1" >> /etc/crontab

- name: Copy Apache or Nginx vhost configuration
  template: src={{suitecrm_vhost_src}} dest={{suitecrm_vhost_dir}}
