---
- debug:
    msg: symfony is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    symfony_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    symfony_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    symfony_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    symfony_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    symfony_name: "{{phpapps_name}}"
    symfony_title: "{{phpapps_title}}"

- debug:
    msg: runtime {{ symfony_vhost_dir }}, {{symfony_vhost_src}}, {{symfony_service}}, {{symfony_owner}}, {{ansible_distribution}}

# symfony
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{symfony_name}}*

- name: Replace Composer repo.packagist to internal repo.packagist
  shell: composer config -g repo.packagist composer https://packagist.phpcomposer.com

- name: Install symfony
  shell: composer create-project symfony/skeleton symfony
  args:
    chdir: /data/wwwroot

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{symfony_name}}" ]; then mv *{{symfony_name}}* {{symfony_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{symfony_vhost_src}} dest={{symfony_vhost_dir}}