---
- debug:
    msg: thinkphp is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    thinkphp_vhost_dir: "{{php_runtime_meta[ansible_os_family][thinkphp_webs].vhost_dir}}"
    thinkphp_vhost_src: "{{php_runtime_meta[ansible_os_family][thinkphp_webs].vhost_src}}"
    thinkphp_service: "{{php_runtime_meta[ansible_os_family][thinkphp_webs].service}}"
    thinkphp_owner: "{{php_runtime_meta[ansible_os_family][thinkphp_webs].owner}}"
    thinkphp_name: "{{phpapps_name}}"
    thinkphp_title: "{{phpapps_title}}"

- debug:
    msg: runtime {{ thinkphp_vhost_dir }}, {{thinkphp_vhost_src}}, {{thinkphp_service}}, {{thinkphp_owner}}, {{ansible_distribution}}


# thinkphp
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{thinkphp_name}}*

- name: Install thinkphp by composer
  shell: composer create-project topthink/think {{thinkphp_name}}

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{thinkphp_name}}" ]; then mv *{{thinkphp_name}}* {{thinkphp_name}}; fi

- name: Copy Apache or Nginx vhost configuration
  template: src={{thinkphp_vhost_src}} dest={{thinkphp_vhost_dir}}
