---
- debug:
    msg: vanilla is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    vanilla_vhost_dir: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_dir}}"
    vanilla_vhost_src: "{{php_runtime_meta[ansible_os_family][phpapps_webs].vhost_src}}"
    vanilla_service: "{{php_runtime_meta[ansible_os_family][phpapps_webs].service}}"
    vanilla_owner: "{{php_runtime_meta[ansible_os_family][phpapps_webs].owner}}"
    vanilla_name: "{{phpapps_name}}"
    vanilla_title: "{{phpapps_title}}"
    vanilla_download_url: "https://github.com/vanilla/vanilla/archive/Vanilla_3.3.zip"

- debug:
    msg: runtime {{ vanilla_vhost_dir }}, {{vanilla_vhost_src}}, {{vanilla_service}}, {{vanilla_owner}}, {{ansible_distribution}}

# vanilla
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{vanilla_name}}*
  
- name: Download from {{ vanilla_download_url }}
  unarchive:
    src: "{{ vanilla_download_url }}"
    dest: /data/wwwroot
    remote_src: yes

- name: Install packages by composer
  shell: composer install
  args:
    chdir: /data/wwwroot/{{vanilla_name}}

- name: Rename dir name
  shell: cd /data/wwwroot; if [ ! -d "{{vanilla_name}}" ]; then mv *{{vanilla_name}}* {{vanilla_name}}; fi

- name: restart mysql
  service: name=mysqld state=restarted enabled=yes

- name: Copy Apache or Nginx vhost configuration
  template: src={{vanilla_vhost_src}} dest={{vanilla_vhost_dir}}