---
- debug:
    msg: vanilla is installing now 

#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php-fpm/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    vanilla_vhost_dir: "{{php_runtime_meta[ansible_distribution][vanilla_webs].vhost_dir}}"
    vanilla_vhost_src: "{{php_runtime_meta[ansible_distribution][vanilla_webs].vhost_src}}"
    vanilla_service: "{{php_runtime_meta[ansible_distribution][vanilla_webs].service}}"
    vanilla_owner: "{{php_runtime_meta[ansible_distribution][vanilla_webs].owner}}"
    vanilla_name: "{{phpapps_name}}"
    vanilla_title: "{{phpapps_title}}"
    vanilla_download_url: "https://github.com/vanilla/vanilla.git"
    vanilla_version: "v3.0.1"

- debug:
    msg: runtime {{ vanilla_vhost_dir }}, {{vanilla_vhost_src}}, {{vanilla_service}}, {{vanilla_owner}}, {{vanilla_webs}}, {{ansible_distribution}}

# 9panel
- name: Enabled 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["{{vanilla.title}}"];'

# vanilla
- name: Remove already existing {{vanilla_name}}
  file:
    path: /data/wwwroot/{{vanilla_name}}
    state: absent

- name: Create Directory
  file:
    path: /data/wwwroot/vanilla
    state: directory
    mode: 0755
  
- name: Download vanilla
  git:
    repo: "{{ vanilla_download_url }}"
    dest: /data/wwwroot/vanilla
    version: "{{vanilla_version}}"

- name: Rename directory name
  shell: mv * {{vanilla_name}}
  args: 
    chdir: /data/wwwroot

- name: replace my.cnf
  copy:
    src: vanilla_my.cnf
    dest: /etc/my.cnf
    mode: 0755

- name: restart mysql
  service: name=mysqld state=restarted enabled=yes

- name: Copy Apache or Nginx vhost configuration
  template: src={{vanilla_vhost_src}} dest={{vanilla_vhost_dir}}